name: superordinaire
favicon: null
layout_spectrum: 0.28919343324378133
typography_spectrum: 0.1113208329770714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.050540339667350054
  lightness: 0.21471630968153477
  saturation: 0.17067973176017404
  rhythmicContrast: 0.231155626475811
purpose: []
